name: mlp_depth
disp_name: lora_test_random_90_10
dir: ""
filenames: /home/woody/iwnt/iwnt164h/mlp_dataset/prospthesisproject-Data/Code/data_split/random_90_10/val_list.txt
resize_to_hw: null
eigen_valid_mask: false
